baseURL = "https://seanybaggins.github.io/physics/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-geekdoc"

#######################
# hugo-geekdoc config #
#######################
pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
#######################
# end of              #
# hugo-geekdoc config #
#######################

